### ISSUE TITLE
Can't see childimagesharp

### ISSUE THREAD

**Issue by Jukez17** [freddydumont/freddydumont.com#20]
I followed your tutorial about json files and images and created the sourceNodes in the `gatsby-node.js`. I have query showing in the graphql explorer but when I click the image i do not see the option there. Any idea why this is happening?

![image](https://user-images.githubusercontent.com/43128825/108994565-a206c980-76a4-11eb-9bf8-1fd969c9e6c4.png)

**Comment by freddydumont** [comment]
See my code in this repo. There's probably something different with yours.
Could also be on Gatsby's side. I know they were working on the image component recently. Could have broken something. If you put your package versions exactly like mine and then it works, that would explain it. 
If you're willing to try that then let me know. If there's a version issue I'll update the blog post.

**Comment by Jukez17** [comment]
I reverted to same sharp versions as you have and still didn't see them. in the graphql explorer. I should have structure very similar to yours in terms of json minus that I have less items in the array but still similar. The sourceNodes is exactly same as your tutorial one but with what i have in the array.

```
exports.sourceNodes = ({ actions, createNodeId, createContentDigest }) => {
    customers.forEach((card) => {
        const {
            image,
            address,
            label,
        } = card

        // name, extension and absolute path are required to build a File node
        const { name, ext } = path.parse(image)
        const absolutePath = path.resolve(__dirname, IMAGE_PATH, image)

        // this data corresponds to a File node that Sharp can process
        const data = {
            name,
            ext,
            absolutePath, // <-- required
            extension: ext.substring(1), // <-- required, remove the dot in `ext`
        }

        // build and create the image node
        const imageNode = {
            ...data,
            id: createNodeId(`card-image-${name}`),
            internal: {
                type: 'CustomerCardImage',
                contentDigest: createContentDigest(data),
            },
        }

        actions.createNode(imageNode)

        const node = {
            // when imageNode is created, the sharp plugin adds childImageSharp to the node
            // so it will be available under the `image` field.
            image: imageNode,
            address,
            label,
            id: createNodeId(`card-${label}`),
            internal: {
                type: 'CustomerCard',
                contentDigest: createContentDigest(card),
            },
        }

        actions.createNode(node)
    })
}
```

**Comment by freddydumont** [comment]
Is your `IMAGE_PATH` setup properly according to your folder structure? I mean there's lots of things you can try to debug. Just console log everything that can be problematic from top to bottom. You should see if something's wrong. 
I'm gonna close this issue now but feel free to post your solution if you find it.
